TransactionController
money-check/MoneyCheckWebApp pull request #22
Opened 2021-12-27 20:51 UTC by SunSual

2021-12-27 21:06 UTC, GusevArtemA requested changes

2021-12-27 21:06 UTC, GusevArtemA commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +            var lastCategory = _context.Categories.LastOrDefault();
Удалить

2021-12-27 21:06 UTC, GusevArtemA commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +            if (lastCategory == null || lastCategory.Id < category.SubCategoryId || _context.Categories.FirstOrDefault(x => x.Id == category.SubCategoryId) == null)
lastCategory == null || lastCategory.Id < category.SubCategoryId  удалить

2021-12-27 21:06 UTC, GusevArtemA commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +            var purchases = _context.Purchases.Where(x => x.CustomerId == userId);
Нет названия категории

2021-12-28 09:16 UTC, DenVot requested changes
Нужна оптимизация pапросами LINQ. Ошибка при построении типов для API

2021-12-28 09:16 UTC, DenVot commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +            foreach (var item in purchases)
Оптимизация кода с помощью LINQ 
```cs
purchases.Select(x => ...)
```

2021-12-28 09:16 UTC, DenVot commented on MoneyCheckWebApp/Types/Debts/DebtorType.cs
> +        public long NaturalMaskId { get; set; }
NaturalMaskId должен быть nullable, т.к. он не обязателен

2021-12-28 09:16 UTC, DenVot commented on MoneyCheckWebApp/Types/Purchases/PurchaseType.cs
> +        public decimal Longitude { get; set; }
Longitude не обязательный, поэтому должен быть nullable

2021-12-28 09:16 UTC, DenVot commented on MoneyCheckWebApp/Types/Purchases/PurchaseType.cs
> +        public decimal Latitude { get; set; }
Latitude не обязательный, поэтому должен быть nullable

2021-12-28 10:31 UTC, DenVot approved these changes
Вроде нормально, но требует тестирования

2021-12-28 10:31 UTC, DenVot commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +                    Longitude = item.Longitude == null ? 0 : (decimal)item.Longitude,
Можно использовать 
```cs
Longitude = item.Longitude ?? 0
```
Относительно `Latitude` также

2021-12-28 10:31 UTC, DenVot commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +                    Longitude = item.Longitude == null ? 0 : (decimal)item.Longitude,
Лишнее приведение типов к `decimal`

2021-12-28 10:31 UTC, DenVot commented on MoneyCheckWebApp/Controllers/TransactionController.cs
> +            var purchases = _context.Purchases.Where(x => x.CustomerId == userId);
Тут ее и не должно быть

2021-12-28 11:47 UTC, GusevArtemA approved these changes

2021-12-28 14:07 UTC, merged